GET http://localhost:8080/books
###
GET http://localhost:8080/books/1
###
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "year": 2008
}

###
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Clean Code - Updated",
  "author": "Robert C. Martin",
  "year": 2008
}
###
DELETE http://localhost:8080/books/1
###
GET http://localhost:8080/books/999

###
DELETE http://localhost:8080/books/999
###
PUT http://localhost:8080/books/999
Content-Type: application/json

{
  "title": "Clean Code - Updated",
  "author": "Robert C. Martin",
  "year": 2008
}